### ISSUE TITLE
Kakoune v2019.01.20 compatibility

### ISSUE THREAD

**Issue by TeddyDD** [alexherbo2/yank-ring.kak#1]
It seems that yank ring doesn't work with newest Kakoune release.

- `:yank-ring-{next,previous}` outputs error: `Paste's timestamp out of date`
- `:yank-ring-open` leaves me in prompt with `Yank Ring` text entered. Pressing
ret causes error: `'try' 2:8: 'delete-buffer' no such buffer '*yank-ring*'`

**Comment by alexherbo2** [comment]
I was experimenting some things.

Does it work now?

**Comment by TeddyDD** [comment]
yup :)

**Comment by alexherbo2** [comment]
You don’t like the new Yank Ring? :(

**Comment by TeddyDD** [comment]
I prefer old one ;)

**Comment by alexherbo2** [comment]
What was your workflow?

**Comment by alexherbo2** [comment]
I should have discussed it before.  What I was trying was to unify the Yank Ring features in a single command, and get rid of the [Select] dependency.

I was quite happy of the incremental search prompt, because we can see in real time where each selection paste stuck.  But in the same time, we lost the Yank Ring Open command which was giving a good bird’s-eye view of the pastes to remind the register.

[Select]: https://github.com/alexherbo2/select.kak

**Comment by TeddyDD** [comment]
I got `y` binded to yank-ring-open in user mode. I don't use yank-ring-{next,previous} at all.

**Comment by alexherbo2** [comment]
@TeddyDD e780c14
