### ISSUE TITLE
[Feature-Request] Search registers content while in fzf

### ISSUE THREAD

**Issue by ivanddm** [alexherbo2/yank-ring.kak#4]
Hi!

I have been using Kakoune recently and installed your `connect.kak` plugin together with this one. I really like to be able to go through the history of my register using `fzf`.

I noticed however that searching while `yank-ring` is activated is kind of meaningless as it only searches for the autogenerated register name, but not for the actual content of the yanked text. It would be great if I can quickly find registers based on its content, perhaps using `fzf-grep`?

I noticed as well that I can pass a regex to the `yank-ring` command and it will give me only the registers that match, but still, I think that the purpose of using `fzf` is to be able to search once it is activated.

Thanks in advance!

**Comment by alexherbo2** [comment]
It could be nice, however it is difficult to search by content through the history with multiple selections.

I choose to offer a list of candidates where you can preview the content of the register in reverse order.

It is close to the yank ring of Emacs, where you can skim through the history with <kbd>Control</kbd> + <kbd>p</kbd> and <kbd>Control</kbd> + <kbd>n</kbd>.

Generally, the yank I want is not too old, and a few <kbd>Control</kbd> + <kbd>p</kbd> allows me to reach the register.

With a grep interface, you will have a list of all the lines and without context, it can be difficult to make sense of what register you will restore.

It was also easier to implement, because I have not to deal with building a JSON dictionary (where the keys would be the display for fzf and the values the info, so I can separate display and content).

I’m open to change the UI if you have more details about the exact behavior.

**Comment by ivanddm** [comment]
> It is close to the yank ring of Emacs, where you can skim through the history with `Control + p` and `Control + n`.

I think this is good enough and `fzf` has a neat UI with preview, so no request from my side on that front. Thanks for clarifying this.

I know that this doesn't belong to this repo, but just wanted to mention that I'm having an issue with your `connect-fzf`'s `fzf-buffers` command. Basically, it doesn't display any results when working in some particular directories (it just gives me an empty `fzf` list). I'll open an issue in that repo instead.

Thanks again!

**Comment by alexherbo2** [comment]
It may be due to a difference between the server directory and your terminal directory.

I thought I handled that.
